openapi: 3.0.3
info:
  title: Api
  description: Api
  version: 1.0.0

tags:
  - name: reports
  - name: front
  - name: users

paths:
  /users:
    $ref: 'specs/users.yaml#/paths/~1users'
  /users/{userName}:
    $ref: 'specs/users.yaml#/paths/~1users~1%7BuserName%7D'
  /users/{userName}/activate:
    $ref: 'specs/users.yaml#/paths/~1users~1%7BuserName%7D~1activate'
  /roles:
    $ref: 'specs/users.yaml#/paths/~1roles'
  /reports:
    $ref: 'specs/reports.yaml#/paths/~1reports'
  /reports/{id}:
    $ref: 'specs/reports.yaml#/paths/~1reports~1%7Bid%7D'
  /reports/{sensorType}/{label}:
    $ref: 'specs/reports.yaml#/paths/~1reports~1%7BsensorType%7D~1%7Blabel%7D'
