openapi: 3.0.0
info:
  title: Factory Data Analytics API
  version: 1.0.0
paths:
  /home/dashboard-config/{userName}:
    get:
      summary: Get dashboard configuration
      operationId: getDashboardConfig
      parameters:
        - in: path
          name: userName
          schema:
            type: string
      tags:
        - home
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardConfig'
    put:
      summary: Update dashboard configuration
      operationId: updateDashboardConfig
      parameters:
        - in: path
          name: userName
          schema:
            type: string
      tags:
        - home
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DashboardConfig'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardConfig'

  /home/events:
    get:
      summary: Get events and alerts
      operationId: getHomeEvents
      tags:
        - home
      parameters:
        - in: query
          name: showOnlyAlerts
          schema:
            type: boolean
        - in: query
          name: searchTerm
          schema:
            type: string
        - in: query
          name: startDate
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

  /home/sensor-values/{userName}:
    get:
      summary: Get current sensor values
      operationId: getHomeSensorValues
      parameters:
        - in: path
          name: userName
          schema:
            type: string
      tags:
        - home
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorValue'

  /home/average-sensor-values/{userName}:
    get:
      summary: Get average sensor values
      operationId: getHomeAverageSensorValues
      parameters:
        - in: path
          name: userName
          schema:
            type: string
      tags:
        - home
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorValue'

  /home/chart-data:
    get:
      summary: Get chart data
      operationId: getHomeChartData
      tags:
        - home
      parameters:
        - in: query
          name: chartConfigIds
          schema:
            type: array
            items:
              type: string
          required: true
        - in: query
          name: timeRange
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: array
                  items:
                    $ref: 'commons.yaml#/components/schemas/SensorData'

components:
  schemas:
    DashboardConfig:
      type: object
      properties:
        userName:
          type: string
        currentSensorValuesConfig:
          type: array
          items:
            $ref: '#/components/schemas/ValueConfig'
        averageSensorValuesConfig:
          type: array
          items:
            $ref: '#/components/schemas/ValueConfig'
        chartConfigs:
          type: array
          items:
            $ref: '#/components/schemas/ChartConfig'

    Event:
      type: object
      properties:
        title:
          type: string
        timestamp:
          type: integer
          format: int64
        isAlert:
          type: boolean

    SensorValue:
      allOf:
        - $ref: '#/components/schemas/ValueConfig'
        - $ref: 'commons.yaml#/components/schemas/SensorData'

    ValueConfig:
      type: object
      properties:
        id:
          type: string
          format: uuid
        label:
          type: string
        sensorType:
          type: string

    ChartConfig:
      type: object
      allOf:
        - $ref: '#/components/schemas/ValueConfig'