openapi: 3.0.3
info:
  title: Reports API
  description: API for creating and retrieving reports
  version: 1.0.0

paths:
  /reports:
    post:
      summary: Creates report with given time window and other parameters
      operationId: createReport
      tags:
        - reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertReportRequest'
      responses:
        '200':
          description: Successfully created report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertReportResponse'
        '403':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

  /reports/search:
    post:
      operationId: searchReports
      tags:
        - reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchReportsRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReportListResponse'
        '403':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

  /reports/{id}:
    get:
      operationId: getReportDetails
      tags:
        - reports
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReportDetailsResponse'
        '403':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

    patch:
      operationId: updateReport
      tags:
        - reports
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertReportRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertReportResponse'
        '403':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

    delete:
      operationId: deleteReport
      tags:
        - reports
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Successful response
        '403':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

  /reports/{sensorType}/{label}:
    get:
      operationId: getSingleReports
      description: Pulls sensor data from given label and time window
      tags:
        - reports
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: to
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: label
          in: path
          schema:
            type: string
        - name: sensorType
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSingleReportResponse'
        '403':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

components:
  schemas:
    Sorting:
      type: object
      properties:
        order:
          enum:
            - asc
            - desc
        name:
          type: string

    Filter:
      type: object
      properties:
        textQuery:
          description: This query is applied for each text field
          type: string
        keywords:
          type: object
          description: Keyword queries. Corresponding keyword queries are mapped to keyword names.
          additionalProperties:
            type: string
        textFields:
          type: array
          items:
            type: string
        from:
          type: integer
          format: int64
        to:
          type: integer
          format: int64
      required:
        - textFields
        - keywords

    SearchReportsRequest:
      type: object
      properties:
        pageSize:
          type: integer
        page:
          type: integer
        sorting:
          type: array
          description: By default uses sorting by score
          items:
            $ref: "#/components/schemas/Sorting"
        filter:
          $ref: "#/components/schemas/Filter"

    UpsertReportRequest:
      type: object
      properties:
        timeRange:
          $ref: 'commons.yaml#/components/schemas/TimeRange'
        sensorLabels:
          type: object
          additionalProperties:
            type: string
        label:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - sensorLabels
        - label
        - name
        - description

    UpsertReportResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid

    GetReportListResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/ReportPreview'

    GetSingleReportResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SensorData'

    ReportPreview:
      type: object
      properties:
        timeRange:
          $ref: 'commons.yaml#/components/schemas/TimeRange'
        id:
          type: string
          format: uuid
        label:
          type: string

    GetReportDetailsResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        timeRange:
          $ref: 'commons.yaml#/components/schemas/TimeRange'
        dataBySensorType:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstantData'

    InstantData:
      type: object
      properties:
        dataByEventKey:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SensorData'

    SensorData:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
        label:
          type: string
        eventKey:
          type: string
          format: uuid
        sensorType:
          type: string
        values:
          type: object
          additionalProperties:
            type: number
